# https://hub.docker.com/r/bitnami/redis-sentinel/
FROM bitnami/redis-sentinel:latest

USER root

COPY ./run-sentinel-entrypoint.sh /opt/bitnami/scripts/redis-sentinel/run-sentinel-entrypoint.sh

RUN chmod +x /opt/bitnami/scripts/redis-sentinel/run-sentinel-entrypoint.sh

ENTRYPOINT [ "/opt/bitnami/scripts/redis-sentinel/run-sentinel-entrypoint.sh" ]
CMD [ "/opt/bitnami/scripts/redis-sentinel/run.sh" ]
