FROM bitnami/redis-cluster:latest

USER root

COPY ./run-create-cluster.sh /run-create-cluster.sh

RUN chown root:root /run-create-cluster.sh
RUN chmod +x /run-create-cluster.sh

#ENTRYPOINT [""]
CMD ["/bin/bash", "-c", "/run-create-cluster.sh"]
