FROM bitnami/redis-cluster:latest

USER root

RUN cp -ra /etc/apt/sources.list /etc/apt/sources.list.backup

COPY ./sources.list /etc/apt/sources.list

RUN apt-get update
RUN apt-get install -y iputils-ping telnet vim

COPY ./run-create-cluster.sh /run-create-cluster.sh

RUN chown root:root /run-create-cluster.sh
RUN chmod +x /run-create-cluster.sh

#ENTRYPOINT [""]
CMD ["/bin/bash", "-c", "/run-create-cluster.sh"]
